Changes to finish recording on mobile session
HabitatMap/AirCastingiOS pull request #112
Opened 2021-07-29 12:32 UTC by jankrzempek

What was done:

Finish recording in now available through action Menu.

https://trello.com/c/CEL1yPL5/186-mobile-active-buttons

2021-07-30 13:44 UTC, pawelgil requested changes

2021-07-30 13:44 UTC, pawelgil commented on AirCasting/AirCastingApp.swift
> +    private let microphoneMenager: MicrophoneManager
typo Menager -> Manager

2021-07-30 13:44 UTC, pawelgil commented on AirCasting/MicrophoneSession/MicrophoneManager.swift
> +    let sessionSynchronizer: SessionSynchronizer
Good thing you used a `protocol` here, but overall I think this class is a huge dump of logic that should really be handled elsewhere. It's usually the case with objects named `Manager` ;) Let's leave it like this for now, but in the future try to find solutions that doesn't touch those classes :)

2021-07-30 13:44 UTC, pawelgil commented on AirCasting/SessionViews/SessionHeaderView.swift
> +    var actionsMenuMobile: some View {
this got huge, let's split stuff into helpers `var/func`

2021-07-30 13:44 UTC, pawelgil commented on AirCasting/SessionViews/SessionHeaderView.swift
> +                Text(session.name ?? "this session")
Strings

2021-07-30 13:44 UTC, pawelgil commented on AirCasting/SessionViews/StreamsView.swift
> +//                .padding(.horizontal)
Don't leave commented out code

2021-07-30 13:44 UTC, pawelgil commented on AirCasting/CoreData/MeasurementStreamStorage.swift
> +        sessionEntity.endTime = Date()
into the perform block it shall go

2021-07-30 13:44 UTC, pawelgil commented on AirCasting/CoreData/MeasurementStreamStorage.swift
> +        let sessionEntity = try context.existingSession(uuid: sessionUUID)
into the perform block it shall go

2021-07-30 15:40 UTC, jankrzempek commented on AirCasting/SessionViews/StreamsView.swift
> +//                .padding(.horizontal)
Of course!

2021-08-04 17:04 UTC, pawelgil approved these changes

2021-08-04 19:52 UTC, merged