Fixed crash when ending BT sessions
HabitatMap/AirCastingiOS pull request #143
Opened 2021-08-13 01:17 UTC by pawelgil

* Made ending synchronization [polymorphic](https://en.wikipedia.org/wiki/Polymorphism_(computer_science))
* We need to sort out dependency injection...

2021-08-13 08:13 UTC, jankrzempek approved these changes
👌🏻

2021-08-13 08:13 UTC, jankrzempek commented on AirCasting/RootAppView.swift
> +                                baseUrl: dependancies.urlProvider), urlProvider: dependancies.urlProvider, measurementStreamStorage: measurementStreamStorage, sessionStoppableFactory: sessionStoppabl
Maybe we can stuck this vertical to be more readable - what is your opinion about that?

2021-08-17 10:18 UTC, smialko requested changes
App doesn't crash but finish session doesn't work either :)

2021-08-17 13:13 UTC, pawelgil commented
> App doesn't crash but finish session doesn't work either :)

@smialko as we discussed this was not implemented at all. I resolved conflicts, please review :)

2021-08-18 07:11 UTC, smialko approved these changes

2021-08-18 10:14 UTC, smialko commented
I'm merging it because I need this for the task I'm working on :)

2021-08-18 11:13 UTC, merged