Date formatting
HabitatMap/AirCastingiOS pull request #223
Opened 2021-09-14 08:38 UTC by jankrzempek

https://trello.com/c/54dZ8Fsr/281-update-date-format-to-mm-dd-yy

2021-09-14 13:07 UTC, pawelgil requested changes

2021-09-14 13:07 UTC, pawelgil commented on AirCasting/SessionViews/SessionHeaderView.swift
>              if string.contains("–") {
I also have some second thoughts here, I think I missed something during the initial review, sorry for that.
The point - is all this work needed at all? If we just need to have a constant format for this why won't we use the [dateTemplate](https://developer.apple.com/documentation/foundation/dateintervalformatter/1407373-datetemplate) for hour formatting and force `en_US` [locale](https://developer.apple.com/documentation/foundation/dateintervalformatter/1409992-locale) to force `MM/dd/yyyy` date formatting?  Like this:
``` Swift
let formatter = DateIntervalFormatter()
formatter.dateTemplate = "HH:mm"
formatter.locale = Locale(identifier: "en_US")
```

Example output for interval within same day: `15:06 – 23:06`
Example output for interval with different days: `9/14/2021, 15:06 – 9/22/2021, 15:06`

2021-09-15 07:52 UTC, jankrzempek commented on AirCasting/SessionViews/SessionHeaderView.swift
>              if string.contains("–") {
I need to say that I've used this solution (maybe wrong) and it gave me 'Sep 27 2021' which is not exactly correct. I made reformat and could you please suggest what to do with this?

2021-09-18 14:55 UTC, pawelgil commented
@jankrzempek after testing this for a while - it crashes in `swapDaysAndMonths` for habitatmap user. I also checked out my recommended solution and it doesn't produce the format you mentioned. It's exactly as I put it in my comment: `9/14/2021, 15:06 – 9/22/2021, 15:06`

2021-09-20 10:06 UTC, jankrzempek commented on AirCasting/SessionViews/SessionHeaderView.swift
>              if string.contains("–") {
I am in shock @pawelgil but it is so awesome.!🥳

2021-09-20 11:23 UTC, pawelgil requested changes

2021-09-20 11:23 UTC, pawelgil commented on AirCasting/Utils/TimeConversion.swift
> +    static func swapDaysAndMonths(date: String) -> String {
I think this not needed anymore?

2021-09-20 17:56 UTC, merged