Fit screen iphone se
HabitatMap/AirCastingiOS pull request #429
Opened 2021-11-17 11:05 UTC by jankrzempek

https://trello.com/c/cu6jE4eo/382-scale-screen-so-it-fits-iphonese

2021-11-19 11:17 UTC, smialko requested changes
Great job! Just please fix the ABMeasurementsView :)

2021-11-19 11:17 UTC, smialko commented on AirCasting/SessionViews/ABMeasurementsView.swift
> -                        .frame(maxWidth: .infinity, alignment: .leading)
Should AB measurements be on the left side of the session card? I think not but tbh I'm not sure. I think that removing the frame and padding moved them to the left. Also, they seem more condensed than previously. 
![IMG_F07B0AE0675D-1](https://user-images.githubusercontent.com/46443841/142613237-d1452fd0-5ae1-4d66-80be-252727c1a5cb.jpeg)

2021-11-19 11:17 UTC, smialko commented on AirCasting/SessionViews/ABMeasurementsView.swift
> -                        .frame(maxWidth: .infinity, alignment: .leading)
Uh, now I see the `Spacer()` - it's its fault the measurements are on the left side.

2021-11-19 11:19 UTC, smialko commented on AirCasting/SessionViews/ABMeasurementsView.swift
> -                        .frame(maxWidth: .infinity, alignment: .leading)
For comparison I'm attaching a photo of how it looked before: 

![image](https://user-images.githubusercontent.com/46443841/142614374-b0fa148a-c9c5-4a4e-92d4-c5b7632e4788.png)

2021-11-24 00:55 UTC, pawelgil approved these changes
Note: I only review the code assuming it's working as expected

2021-11-25 09:40 UTC, smialko reviewed
it's better now! 😄

2021-11-25 09:40 UTC, smialko commented on AirCasting/SessionViews/ABMeasurementsView.swift
> +                    Spacer()
I don't think using a Spacer() here is a good idea, right now the AB parameters are squeezed in the middle and there's too much space on the sides. Maybe try to use horizontal `.padding()` instead? :)

2021-11-25 09:40 UTC, smialko commented on AirCasting/SessionViews/ABMeasurementsView.swift
> +                    Spacer()
Here is just an example, don't hesitate to do it another way:

```
private var streamNames: some View {
        return HStack {
            Group {
                ForEach(streamsToShow, id : \.self) { stream in
                    SingleMeasurementView(stream: stream,
                                          threshold: nil,
                                          selectedStream: $selectedStream,
                                          isCollapsed: $isCollapsed,
                                          measurementPresentationStyle: .hideValues,
                                          isDormant: session.isDormant)
                    streamsToShow.count == 1 ? Spacer() : nil
                }
            }
            .padding(.horizontal)
        }
    }
```

2021-11-25 13:36 UTC, merged