Added settings page
HabitatMap/AirCastingiOS pull request #60
Opened 2021-06-18 14:15 UTC by jankrzempek

https://trello.com/c/3vxiFRbo/4-settings-for-profile-mvp-view

2021-06-21 06:43 UTC, mateuszmackowiak commented on AirCasting/Settings/MyAccountView.swift
> +                Text("You aren’t currently logged in")
in such cases where the logic isn't finished please add a TODO

2021-06-21 06:43 UTC, mateuszmackowiak commented on AirCasting/Settings/MyAccountView.swift
> +                Text("You aren’t currently logged in")
Or this screen has an invalid name.

2021-06-21 06:43 UTC, mateuszmackowiak commented on AirCasting/Settings/MyAccountViewSingOut.swift
> +                Text("You are currently logged in as jan.krzempek@lunarlogic.io")
please add a todo.

2021-06-21 06:43 UTC, mateuszmackowiak commented on AirCasting/Settings/SettingsView.swift
> +   private struct FullScreenModalView: View {
Please think of a better name

2021-06-22 22:27 UTC, pawelgil requested changes
Lets make it a bit cleaner 🧹
\ also minor typos

2021-06-22 22:27 UTC, pawelgil commented on AirCasting/Settings/SettingsView.swift
> +    @State private var isToggle : Bool = false
I know it's nit-picky, but the usual styling (in the app too afaict) is to put a colon after the name without any spaces:

```Swift
@State private var isToggle: Bool = false
```

2021-06-22 22:27 UTC, pawelgil commented on AirCasting/Settings/MyAccountViewSingOut.swift
> +struct MyAccountViewSingOut: View {
typo `SingOut` -> `SignOut`

2021-06-22 22:27 UTC, pawelgil commented on AirCasting/Settings/MyAccountView.swift
> +                } .buttonStyle(BlueButtonStyle())
remove space between `}` and `.` plz

2021-06-22 22:27 UTC, pawelgil commented on AirCasting/Settings/MyAccountView.swift
> +}
I think this body would be much more readable if we got rid of the unneeded details at the `body` level. [Top-level functions](https://stackoverflow.com/questions/633617/whats-the-difference-between-low-level-functions-top-level-functions) (computed var here is really a function with no paramaters, `var` is just Swift syntactic sugar) should really be screaming their intent, hiding any unneeded implementation detail in some private functions below. Anyone that wants to know the details would just scroll down to the part they are interested in and read it and everyone elses time is saved by making this high-level concept really easy to read thru. An example how this particular code can be divided:

```Swift
var body: some View {
    ZStack {
        VStack(alignment: .leading) {
            #warning("Logic here needs to be finished - handle log in")
            loggedOutInformationLabel
            createAccountButton
            logInButton
            Spacer()
        }
    }
    .navigationTitle("My account")
}

private var loggedOutInformationLabel: some View {
    Text("You aren’t currently logged in")
        .foregroundColor(.aircastingGray)
        .padding()
}

private var createAccountButton: some View {
    Button(action: {
    }) {
        Group {
            HStack {
                Text("Create an account")
                Spacer()
                Image(systemName: "chevron.right")
            }
            .padding(.horizontal)
        }
    }
    .buttonStyle(BlueButtonStyle())
    .padding()
}

private var logInButton: some View {
    Button(action: {
    }) {
        Group {
            HStack {
                Text("Login in")
                Spacer()
                Image(systemName: "chevron.right")
            }
            .padding(.horizontal)
            .padding(.vertical, 12)
        }
        .overlay(
            RoundedRectangle(cornerRadius: 5)
                .stroke(lineWidth: 1.0)
        )
    }
    .padding()
}
```

This simple little division makes it super-clear how this view looks like at just first glance.

2021-06-22 22:27 UTC, pawelgil commented on AirCasting/Settings/MyAccountViewSingOut.swift
> +    var body: some View {
here the `body` is less complicated, but IMO would still benefit from making same thing as above (your call)

2021-06-22 22:27 UTC, pawelgil commented on AirCasting/Settings/SettingsView.swift
>      var body: some View {
this is a huge body function over here, let's try to cut it into smaller pieces like in the example above and to make it more readable this way

2021-06-23 13:32 UTC, pawelgil requested changes
great job on applying clean code techniques! Let's rename one more thing and cleanup missed string literal and we'll be good to go here

2021-06-23 13:32 UTC, pawelgil commented on AirCasting/Settings/MyAccountView.swift
> +    Text("You aren’t currently logged in")
missed this one, can go to `Strings` struct also :)

2021-06-23 13:32 UTC, pawelgil commented on AirCasting/Settings/SettingsView.swift
> +                    showModalButton
good job on dividing stuff over here. One thing that can be better is this name. "showModalButton" is not really carrying any intent description. 'Modal' is just a presentation style, so showModalButton is saying nothing. Maybe lets think of a better name (from what I see here this button navigates the user to some backend settings, so maybe something like `navigateToBackendSettingsButton` ? )

2021-06-23 13:32 UTC, pawelgil commented on AirCasting/Settings/SettingsView.swift
> +                cancelButton
nice cleanup! 🧹

2021-06-23 21:02 UTC, pawelgil approved these changes
🔥

2021-06-24 08:26 UTC, merged