Refactor of ChooseSessionTypeView.
HabitatMap/AirCastingiOS pull request #604
Opened 2022-02-16 09:47 UTC by jankrzempek

Deleted BT Manager which was doing nothing there. Moved VM to it's view init. Structured code into easier redable parts.

2022-02-16 15:28 UTC, pawelgil approved these changes

2022-02-17 12:13 UTC, anna1901 requested changes
Doesn't work on ios14.

2022-02-17 12:13 UTC, anna1901 commented on AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
> -        if #available(iOS 15, *) {
Did you replace it with anything? I can't find it and the view doesn't work on ios14.

2022-02-17 15:29 UTC, anna1901 approved these changes

2022-02-17 15:29 UTC, anna1901 commented on AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
> +                                .fullScreenCover(isPresented: .init(get: {
Why do we need this workaround with init?

2022-02-21 15:24 UTC, merged