Adjusted code to be more generic and improved UI.
HabitatMap/AirCastingiOS pull request #680
Opened 2022-04-19 14:11 UTC by jankrzempek

https://trello.com/c/eSLDiuQk/631-applied-changes-to-parameters

https://trello.com/c/4K1Dt8Cv/635-improve-searching-for-purpleair-and-airbeam-data-to-search-feature

2022-04-20 19:53 UTC, SzymonGorowski approved these changes
Looks good!

2022-04-21 14:45 UTC, pawelgil requested changes
small styling stuff needed

2022-04-21 14:45 UTC, pawelgil commented on AirCasting/SearchAndFollow/MapSessionsDownloader/APIStruct/MapDownloaderMeasurementType.swift
> +    var apiNameSufix: String {
typo: `Suffix`. It should probably also be renamed to something better... How about `sensorNameSuffix` (see also the prefix name change proposition)

2022-04-21 14:45 UTC, pawelgil commented on AirCasting/SearchAndFollow/MapSessionsDownloader/APIStruct/MapDownloaderSensorType.swift
> +    var apiNamePrefix: String {
and here maybe `sensorNamePrefix` ?

2022-04-21 14:45 UTC, pawelgil commented on AirCasting/SearchAndFollow/SearchLocation/SearchViewModel.swift
> +    func onParameterTap(with param: String) {
a bit messy structure in this file. Please move all `public` methods above `private` ones to improve readability (and do the same with properties)

2022-04-21 14:45 UTC, pawelgil commented on AirCasting/SearchAndFollow/SearchLocation/SearchViewModel.swift
> +    init() {
move init between properties and functions (this is the most followed convention)

2022-04-26 16:57 UTC, pawelgil approved these changes

2022-04-28 06:42 UTC, merged