Make image smaller so that user can access GetStarted button.
HabitatMap/AirCastingiOS pull request #818
Opened 2022-07-25 10:36 UTC by jankrzempek

https://trello.com/c/DRsxTWfP/764-ipad-landscape-intro-wizard-first-screen-cut-off-cant-continue

🚩This is the temporary, not ideal fix. As soon as Gosia will be back, I will reach out to her to get images designed specifically for iPad.

2022-07-25 10:45 UTC, SzymonGorowski approved these changes
Approved 😄

2022-07-25 11:55 UTC, anna1901 requested changes
I don't like that it is stretched like that. I think it would be better to change how this image is added to this view and add it as a background image instead

2022-07-25 14:05 UTC, jankrzempek commented
> I don't like that it is stretched like that. I think it would be better to change how this image is added to this view and add it as a background image instead

What do you mean by background, could you please elaborate or give an example?

2022-07-25 14:08 UTC, anna1901 reviewed
Add image as a background image using `.background()`. I'm not sure how I can elaborate on this. We can have a call if I should provide you some more information.

2022-07-26 13:23 UTC, merged

2022-07-26 13:24 UTC, anna1901 commented on AirCasting/Assets.xcassets/Bitmap.imageset/Contents.json
> +      "idiom" : "ipad",
This shouldn't be here, right?

2022-07-26 13:24 UTC, anna1901 commented on AirCasting/Onboarding/GetStarted.swift
> +        }.background(
new line?